services:
    miniwhoami_20412:
      restart: always
      image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
      container_name: "miniwhoami_20412"
      ports:
        - 20412:80
      networks:
        - mynetwork

    miniwhoami_20413:
      restart: always
      image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
      container_name: "miniwhoami_20413"
      ports:
        - 20413:80
      networks:
        - mynetwork

networks:
    mynetwork:
      name: mynetwork