apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: miniwhoami-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: miniwhoami
  template:
    metadata:
      name: miniwhoami
      labels:
        app: miniwhoami
    spec:
        containers:
        - name: miniwhoami
          image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami