apiVersion: v1
kind: Pod
metadata:
  name: miniwhoami
spec:
  containers:
  - image: jennerwein/miniwhoami-crash
    name: miniwhoami
    livenessProbe: 
      httpGet: 
        path: / 
        port: 8080 
      initialDelaySeconds: 20