apiVersion: v1
kind: Pod
metadata:
  name: miniwhoami-manual-pod2
  labels:
    hochschule: hbrs
    sem: ws22
spec:
  containers:
    - name: miniwhoami-manual-pod2
      image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
      ports:
        - containerPort: 80