apiVersion: v1
kind: ReplicationController
metadata:
  name: miniwhoami-rc
spec:
  replicas: 3
  selector:
    app: miniwhoami
  template:
    metadata:
      labels:
        app: miniwhoami
    spec:
      containers:
      - name: miniwhoami
        image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
        ports:
        - containerPort: 80