- name: Install apt-transport-https
  ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true


- name: Add signing key
  ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present


- name: Docker Registry/Repository
  apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present



- name: Install Docker-CE and Docker-Compose
  ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: Adding Ansible user
  user: name=migbin2s
    groups=docker
    append=yes
  become: true

