services:
  load-balancer:
    container_name: load-balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      my_ipv6:
        ipv6_address: 2001:638:408:200:ff6c:cafe::9999
      loc_ipv6:
    restart: unless-stopped

  miniwhoami-s1:
    container_name: miniwhoami-s1
    image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
    networks:
      loc_ipv6:
    restart: unless-stopped

  miniwhoami-s2:
    container_name: miniwhoami-s2
    image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
    networks:
      loc_ipv6:
    restart: unless-stopped

  miniwhoami-s3:
    container_name: miniwhoami-s3
    image: docker.fslab.de/migbin2s/servmgmt-ws22/miniwhoami
    networks:
      loc_ipv6:
    restart: unless-stopped



networks:
  my_ipv6:
    name: my_ipv6
    external: true
  loc_ipv6:
    name: loc_ipv6
    external: true
